name: Checkmarx SAST 9.7 (On-Prem)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sast_scan:
    # dùng runner nội bộ (Windows) của bạn
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Gửi source lên CxSAST 9.x và trigger scan
      - name: Run Checkmarx SAST
        uses: checkmarx-ts/checkmarx-github-action@v2
        with:
          cxServer:   ${{ secrets.CX_SERVER }}
          cxUsername: ${{ secrets.CX_USER }}
          cxPassword: ${{ secrets.CX_PASS }}
          cxTeam:     ${{ secrets.CX_TEAM || '\CxServer' }}
          projectName: "test-checkmarx"
          preset: "Checkmarx Default"
          # Nếu repo lớn hoặc cần nhanh hơn sau lần đầu:
          # incremental: true
