name: Checkmarx SAST 9.7 (On-Prem)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sast_scan:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkmarx SAST
        # ↓ đổi v2 thành v1
        uses: checkmarx-ts/checkmarx-github-action@v1
        env:
          # Nếu server dùng chứng chỉ tự ký, bật dòng này để thử nhanh (sau đó hãy import CA cho chuẩn)
          # NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          cxServer:   ${{ secrets.CX_SERVER }}   # ví dụ: https://nfrcxsast
          cxUsername: ${{ secrets.CX_USER }}     # admin_sast
          cxPassword: ${{ secrets.CX_PASS }}
          cxTeam:     ${{ secrets.CX_TEAM || '\CxServer' }}
          projectName: "test-checkmarx"
          preset: "Checkmarx Default"
          # incremental: true
